# REPEL Data

Noam Ross, Emma Mendelsohn, Rob Young

---

## Overview

This package serves as a client interface for accessing the REPEL project database from R. It is currently EHA-only, but may become a public package for database access.

The REPEL database contains data curated from multiple sources of animal disease occurrence and covariates of disease spread (e.g., trade, animal movement). The database is regularly updated as new data becomes available. Here, we provide installation and usage instructions, followed by an overview of the tables in the database.

## Database structure 

Below is a high-level overview of all tables in the database. Descriptions of table fields can be viewed as a tibble with `repeldata::repel_fields_schema()` [WORK IN PROGRESS]

### Disease Tables

These tables contain disease reports and supplementary country attribute and health infrastructure information extracted from the [World Animal Health Information Database](https://wahis.oie.int/#/report-management) (WAHIS). Managed by the World Organization for Animal Health (OIE), WAHIS contains annual disease summary reports and individual disease outbreak reports from 174 countries and territories. We download these reports from the OIE API and standardize them into structured tables.

#### Annual report tables

Annual report tables include summaries by 6-month semesters (Jan - Jun and Jul - Dec) and by year. 

* __annual_reports_status__  
Indicates whether reports are available through WAHIS for all countries, years, and semesters

* __annual_reports_ingest_status_log__  
Indicates whether reports available through WAHIS were successfully downloaded and included in the REPEL database. Error messages are provided for reports that were not successfully included.  

* __annual_reports_submission_info__  
Point of contact information from country submitters 

* __annual_reports_animal_diseases__  
Diseases present, suspected, or absent in animals. Includes counts of new and total outbreaks if available. Disease names are standardized to the [Animal Disease Ontology](http://agroportal.lirmm.fr/ontologies/ANDO]) from the French National research institute for agriculture, food and the environment.

* __annual_reports_animal_diseases_detail__  
Data from annual_reports_animal_diseases broken down at finer temporal and spatial scales

* __annual_reports_disease_humans__  
Diseases present or absent in humans. Includes counts of human cases and deaths if available. Disease names are standardized to the [Animal Disease Ontology](http://agroportal.lirmm.fr/ontologies/ANDO]) from the French National research institute for agriculture, food and the environment.

* __annual_reports_diseases_unmatched__  
Disease names that were not successfully matched against the ANDO database. These require manual review. Note that the unstandardized disease reports are included in the database.

* __annual_reports_animal_hosts__  
Animal diseases by taxa. Includes counts of cases, deaths, vaccinations, etc.

* __annual_reports_animal_hosts__  
Data from annual_reports_animal_diseases broken down at finer temporal and spatial scales

* __annual_reports_animal_population__  
Reported populations of animals by country

* __annual_reports_veterinarians__  
Counts of veterinarians by country

* __annual_reports_national_reference_laboratories__  
Names and contact information for testing laboratories within countries

* __annual_reports_national_reference_laboratories_detail__  
Laboratory testing capability by disease

* __annual_reports_vaccine_manufacturers__  
Names and contact information for vaccine production laboratories within countries

* __annual_reports_vaccine_manufacturers_detail__  
Vaccine production capability by disease

* __annual_reports_vaccine_production__  
Vaccine doses produced and exported

#### Outbreak report tables

Outbreak tables are are individual disease reports from data released on a weekly basis. Outbreaks are tracked as threads with new events continuously reported until the outbreak is resolved or the disease becomes endemic. 
  
* __outbreak_reports_ingest_status_log__  
List of reports in database. `report_info_id` can be appended to "https://wahis.oie.int/pi/getReport/" to see the report API.

* __outbreak_reports_events__  
High-level event information including country, disease and disease status. Disease names are standardized to the [Animal Disease Ontology](http://agroportal.lirmm.fr/ontologies/ANDO]) from the French National research institute for agriculture, food and the environment. Each row is an outbreak report. `report_id` is the unique report ID.

* __outbreak_reports_outbreaks__  
Detailed location and impact data for outbreak events. This table can be joined with `outbreak_reports_events` by `report_id`. `outbreak_location_id` is a unique ID for each location (e.g, farm or village) within a outbreak.

* __outbreak_reports_diseases_unmatched__  
Disease names that were not successfully matched against the ANDO database. These require manual review. Note that these diseases are not removed from the database.

### Connect Tables

These tables contain non-disease endpoints from multiple sources representing covariates of disease spread. Connect data are values shared between two countries (e.g., trade value). 

* __connect_static_vars__  
Connect values without a temporal component. Static data are non-directional, meaning that values from Country A -> Country B are the same as values from B -> A. This table contains the following data:  

  * Shared borders (True or False)
  * Geodesic distance between country centroids in meters
  * Number of migratory birds shared by countries based on country migratory avian species lists from [BirdLife International](http://datazone.birdlife.org/country).
  * Number of migratory non-avian wildlife shared by countries based on country species lists from the [IUCN Red List API](https://apiv3.iucnredlist.org/) and the global migratory species list from the [Global Register of Migratory Species](http://groms.de/groms_neu/view/order_stat_patt_spanish.php?search_pattern=).  
  
* __connect_yearly_vars__  
Connect values that vary by year. Yearly data are directional, meaning that values from Country A -> Country B differ from values from B -> A.  

  * Number of human migrants from the [United Nations Population Division Global Migration Database](https://www.un.org/en/development/desa/population/migration/data/empirical2/index.asp)
  * Number of tourists from the [United Nations World Tourism Organization](https://www.e-unwto.org/)
  * Count of traded livestock heads from the [Food and Agriculture Organization](http://www.fao.org/faostat/en/#data/)
  * Trade dollars from the Open Trade Statistics API, accessed using the [tradestatistics](https://cran.r-project.org/web/packages/tradestatistics/tradestatistics.pdf) R package  
  
* __connect_fao_lookup__  
Descriptions of item codes from livestock heads fields in connect_yearly_vars

* __connect_ots_lookup__  
Descriptions of product codes from trade dollars fields in connect_yearly_vars